// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RomsBrowse.Data;

#nullable disable

namespace RomsBrowse.Data.Migrations.SQLite
{
    [DbContext(typeof(SQLiteContext))]
    [Migration("20240707105639_AddedSqlite")]
    partial class AddedSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("RomsBrowse.Data.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmulatorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Folder")
                        .IsUnique();

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("RomsBrowse.Data.Models.RomFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlatformId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileName");

                    b.HasIndex("PlatformId");

                    b.ToTable("RomFiles");
                });

            modelBuilder.Entity("RomsBrowse.Data.Models.SaveData", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RomFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasMaxLength(1048576)
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasMaxLength(1048576)
                        .HasColumnType("BLOB");

                    b.HasKey("UserId", "RomFileId", "Flags");

                    b.HasIndex("Created");

                    b.HasIndex("RomFileId");

                    b.HasIndex("UserId", "RomFileId")
                        .IsUnique();

                    b.ToTable("SaveData");
                });

            modelBuilder.Entity("RomsBrowse.Data.Models.Setting", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("RomsBrowse.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastActivity");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RomsBrowse.Data.Models.RomFile", b =>
                {
                    b.HasOne("RomsBrowse.Data.Models.Platform", "Platform")
                        .WithMany("RomFiles")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("RomsBrowse.Data.Models.SaveData", b =>
                {
                    b.HasOne("RomsBrowse.Data.Models.RomFile", "RomFile")
                        .WithMany("SaveData")
                        .HasForeignKey("RomFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RomsBrowse.Data.Models.User", "User")
                        .WithMany("SaveData")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RomFile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RomsBrowse.Data.Models.Platform", b =>
                {
                    b.Navigation("RomFiles");
                });

            modelBuilder.Entity("RomsBrowse.Data.Models.RomFile", b =>
                {
                    b.Navigation("SaveData");
                });

            modelBuilder.Entity("RomsBrowse.Data.Models.User", b =>
                {
                    b.Navigation("SaveData");
                });
#pragma warning restore 612, 618
        }
    }
}
